[[plugins]]
repo = 'neoclide/coc.nvim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = { 'colorscheme': 'wombat' }
    set laststatus=2
    set noshowmode
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
  let g:highlightedyank_highlight_duration = 150
'''

[[plugins]]
repo = 'skanehira/gh.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tyru/caw.vim.git'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active = 1
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  GoInstallBinaries
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'sickill/vim-monokai'

[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'LumaKernel/fern-mapping-fzf.vim'

[[plugins]]
repo = 'zefei/vim-wintabs'

[[plugins]]
repo = 'iberianpig/tig-explorer.vim'

[[plugins]]
repo = 'sebdah/vim-delve'
