[[plugins]]
repo = 'preservim/vim-colors-pencil'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = 'call coil398#init#coc#hook_source'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = { 'colorscheme': 'wombat' }
    set laststatus=2
    set noshowmode
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
  let g:highlightedyank_highlight_duration = 150
'''

[[plugins]]
repo = 'skanehira/gh.vim'
